### ISSUE TITLE
Module not fount cannot resolve.

### ISSUE THREAD

**Issue by mazer-rakham** [gnbaron/use-lodash-debounce#1]
package.json
![image](https://user-images.githubusercontent.com/11220261/69452880-cd2b9c00-0d30-11ea-86b0-a94499b2b112.png)
File:
![image](https://user-images.githubusercontent.com/11220261/69452906-dae12180-0d30-11ea-83d2-74bae6917c50.png)
Output:
![image](https://user-images.githubusercontent.com/11220261/69452932-e6344d00-0d30-11ea-9687-6623c07421e3.png)

**Comment by mazer-rakham** [comment]
I solved this by installing lodash.debouce

**Comment by martinadjust** [comment]
yeah 

npm i --save lodash.debounce

did the trick!

**Comment by gnbaron** [comment]
Glad you've figured it out!

Just FYI, as mentioned in the [README.md](https://github.com/gnbaron/use-lodash-debounce/blob/master/README.md), `react` and `lodash.debounce` are peer dependencies, which means your project should provide them.

> Notice that react and lodash.debounce are defined as peer dependencies in order to get a smaller bundle size. This means they should be installed in your project.

This brings some flexibility as you can install whatever version you want of them and avoid duplicated dependencies.

**Comment by mazer-rakham** [comment]
Yeah i am an idiot. I should actually read read.me's lol

**Comment by gnbaron** [comment]
No worries 🙂
