### ISSUE TITLE
Getting "unable to resolve dependency tree" when trying to install with React 18+

### ISSUE THREAD

**Issue by JPStrydom** [gnbaron/use-lodash-debounce#25]
It seems like React 18 and above is not listed as a valid dependency, but when force installing the module it seems to work. So I suspect React 18 just needs to be added as a valid peer dependencies.

Error From NPM:
![image](https://user-images.githubusercontent.com/25905330/182880561-49a1658d-68e4-4cd7-a6d4-d83a8b9a1622.png)

A simple fix for this could potentially be to just update the peer dependency list in the `package.json` file to the following:
```
"peerDependencies": {
    "lodash.debounce": "^4.0.8",
    "react": "^16.9.0 || 17.x || 18.x"
  },
```

**Comment by JPStrydom** [comment]
Made a [PR](https://github.com/gnbaron/use-lodash-debounce/pull/26) with the fix 👍 Do you have a rough ETA on when we can expect the package update to be released on NPM?

**Comment by gnbaron** [comment]
Thanks @JPStrydom! I will try to do that over the weekend.
