### ISSUE TITLE
debounce's return val isn't being preserved

### ISSUE THREAD

**Issue by k-funk** [gnbaron/use-lodash-debounce#8]
The convention for lodash.debounce is to keep a reference to the return value of `debounce`, and `cancel` should generally only be called once for cleanup (usually on unmount).

However, `debounce` is actually getting called many times, as is `cancel`.  So while this does work and things do get cleaned up properly, I think it kinda defeats the purpose of using lodash in the first place.

I'm new to TS and hooks, so I don't have a solution, but just curious if you were aware that this is happening.

**Comment by gnbaron** [comment]
Yeah, this is what causes #3 probably. I didn't have time to get to this yet, but will try to take a look soon. Closing. I will close this one and let #3 keep track of it.
